main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views
from main.views import robots_txt

urlpatterns = [
    #url(r'^$', views.index),
    path('', views.index),
    #url(r'^robots.txt', robots_txt),
    path('robots.txt', robots_txt),
    #url(r'^c/(?P<short_name>[0-9a-z\-]+)/$', views.entries_by_category_list),
    path('c/<slug:short_name>/', views.entries_by_category_list),
    #url(r'^t/(?P<short_name>[0-9a-z\-]+)/$', views.entries_by_tag_list),
    path('t/<slug:short_name>/', views.entries_by_tag_list),
    #url(r'^e/(?P<id>[0-9]+)/$', views.entry),
    path('e/<int:id>/', views.entry),
    #url(r'^json/app_entries$', views.get_app_entries_json),
    re_path('^json/app_entries$', views.get_app_entries_json),
    #url(r'^json/tags$', views.get_tags_json),
    re_path('^json/tags$', views.get_tags_json),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.COMMON_MEDIA_URL, document_root=settings.COMMON_MEDIA_ROOT)

workgroup/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.apps import apps

handler404 = 'main.views.redirect_old_web'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('m/', include('main_menu.urls')),
    path('', include('main.urls'))
    # , path('afiliacio/', include('afiliacio.urls'))
]

if apps.is_installed('assessoraments'):
    urlpatterns.insert(0, path('assessoraments/', include('assessoraments.urls')))

if apps.is_installed('calculs'):
    urlpatterns.insert(0, path('calculs/', include('calculs.urls')))

if apps.is_installed('especialitat_borsa'):
    urlpatterns.insert(0, path('especialitat_borsa/', include('especialitat_borsa.urls')))

if apps.is_installed('dades_plantilles'):
    urlpatterns.insert(0, path('dades_plantilles/', include('dades_plantilles.urls')))

if apps.is_installed('simple_pages'):
    urlpatterns.insert(0, path('p/', include('simple_pages.urls')))

if apps.is_installed('afiliacio'):
    urlpatterns.insert(0, path('afiliacio/', include('afiliacio.urls')))

main/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from ordered_model.models import OrderedModel
import html
import re

# Entries tags
class Tag(OrderedModel):
    short_name = models.CharField(max_length=50, verbose_name='Nom curt')
    name = models.CharField(max_length=100, verbose_name='Nom')
    body = RichTextUploadingField(blank=True, verbose_name='Cos')
    # Tags that are not in a category will not be listed in the menu
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Categoria')
    color = models.CharField(max_length=7, blank=True, verbose_name='Color')
    is_hidden = models.BooleanField(default=False, verbose_name='Etiqueta oculta')
    order_with_respect_to = 'category'
    class Meta(OrderedModel.Meta):
        verbose_name = 'etiqueta'
        verbose_name_plural = 'etiquetes'
        ordering = ['order']
    def __str__(self):
        return self.name

# Tags are in a category
class Category(OrderedModel):
    short_name = models.CharField(max_length=50, verbose_name='Nom curt')
    name = models.CharField(max_length=50, verbose_name='Nom')
    body = RichTextUploadingField(blank=True, verbose_name='Cos')
    visible = models.BooleanField(default=True)
    class Meta(OrderedModel.Meta):
        verbose_name = 'categoria'
        verbose_name_plural = 'categories'
    def tags(self):
        return Tag.objects.filter(category=self.id)
    def __str__(self):
        return self.name

# Class with any content
class Entry(OrderedModel):
    summary = RichTextUploadingField(config_name='basic', verbose_name='Resum')
    body = RichTextUploadingField(blank=True, verbose_name='Cos')
    main_image = models.ImageField(upload_to='main_images/', blank=True, verbose_name='Imatge Principal')
    is_featured = models.BooleanField(verbose_name='Entrada destacada')
    featured_order = models.PositiveSmallIntegerField(default=0, blank=True, verbose_name="Ordre entrada destacada")
    is_in_front_page = models.BooleanField(default=True, verbose_name='Està a la pàgina principal')
    show_in_app = models.BooleanField(default=True, verbose_name='Mostra a l\'app')
    tags = models.ManyToManyField(Tag, verbose_name='Etiquetes')
    date_time = models.DateTimeField(default=timezone.now, verbose_name='Data i hora')
    class Meta(OrderedModel.Meta):
        verbose_name = 'entrada'
        verbose_name_plural = 'entrades'
    
    # Check if all tags of this entry are hidden. If so, date will not be shown
    def all_tags_hidden(self):
        for tag in self.tags.all():
            if not tag.is_hidden:
                return False
        return True
    
    def __str__(self):
        # Regular expression to search tags
        p = re.compile(r'<.*?>')
        # Remove tags in summary and decode HTML entities and references
        summary_without_tags = html.unescape(p.sub('', self.summary))
        # Return the resulting string shortened to 100 characters
        return summary_without_tags[0:100] + "..." if len(summary_without_tags)>100 else summary_without_tags

posters/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from ordered_model.models import OrderedModel

common_media_storage = FileSystemStorage(location=settings.COMMON_MEDIA_ROOT, \
                                         base_url=settings.COMMON_MEDIA_URL)

# Posters showed in main page
class Poster(OrderedModel):
    title = models.CharField(max_length=100, verbose_name='Títol')
    date_time = models.DateTimeField(auto_now_add=True)
    visible = models.BooleanField(default=True)
    class Meta(OrderedModel.Meta):
        verbose_name = 'cartell'
        verbose_name_plural = 'cartells'
    def __str__(self):
        return self.title

# A poster can have more than one image. If it has more than one image it will
# be a carousel.
class PosterImage(models.Model):
    alt = models.CharField(max_length=100, verbose_name='Text alternatiu', \
                           blank=True, null=True,)
    image = models.ImageField(storage=common_media_storage, \
                              upload_to='posters/', \
                              verbose_name='Imatge del cartell')
    link = models.CharField(max_length=200, \
                            blank=True, null=True,
                            verbose_name='Enllaç')
    poster = models.ForeignKey('Poster', verbose_name='Cartell', \
                               on_delete=models.CASCADE,)
    landscape_mode = models.BooleanField(default=False, verbose_name='Posar la imatge apaisada')

main/views.py
from django.apps import apps
from django.conf import settings
from django.shortcuts import get_object_or_404, render, redirect
from django.http import JsonResponse
from .models import Category
from .models import Entry
from .models import Tag
from .utils import get_common_info, get_entries_per_page
from django.http.response import HttpResponse
from django.views.decorators.http import require_GET

def index(request):
    # Disable web if vaga
    if apps.is_installed('config' ):
        Config = apps.get_model('config', 'Config')
        vaga_general = Config.objects.filter(key='VAGA_GENERAL').first()
        if vaga_general is not None and vaga_general.value != '':
            # If URL is sindicat.net?entra, allow to visit the web
            if not request.META.get('QUERY_STRING') == 'entra':
                return redirect(vaga_general.value);
    # Get common info of all templates
    context = get_common_info(request)
    # Get the rest of entries
    all_entries = Entry.objects.all().filter(is_in_front_page=True).order_by("-is_featured","featured_order","order")
    # Get which page we must display and get the corresponding entries
    page = request.GET.get('page')
    entries = get_entries_per_page(page, all_entries)
    if apps.is_installed('nomenaments') and apps.is_installed('departament'):
        context.update(nomenaments_installed=True)
        ServeiTerritorial = apps.get_model('departament', 'ServeiTerritorial')
        sts = ServeiTerritorial.objects.all()
        context.update(sts=sts)
        NomenamentNumero = apps.get_model('nomenaments', 'NomenamentNumero')
        nomenaments_num_today = NomenamentNumero.get_nomenaments_num_dict()
        context.update(nomenaments_num=nomenaments_num_today)
    # Show or not right column depending on settings
    if hasattr(settings, 'RIGHT_COLUMN'):
        show_right_column = settings.RIGHT_COLUMN
    else:
        show_right_column = True
    context.update(show_right_column=show_right_column)
    # Return data to the template
    context.update(entries=entries)
    return render(request, 'main/index.html', context)

def entries_by_tag_list(request, short_name):
    tag = Tag.objects.get(short_name=short_name)
    # Get common info of all templates
    context = get_common_info(request)
    # Get entries with tag ordered by date_time in descending order
    all_entries = Entry.objects.filter(tags__in=[tag]).order_by("-is_featured","featured_order","order")
    # Get which page we must display and get the corresponding entries
    page = request.GET.get('page')
    entries = get_entries_per_page(page, all_entries)
    # Return data to the template
    context.update(entries=entries, current_tag=tag)
    return render(request, 'main/entries_by_tag_list.html', context)

def entries_by_category_list(request, short_name):
    category = Category.objects.get(short_name=short_name)
    # Get common info of all templates
    context = get_common_info(request)
    # Get all category tags
    tags = Tag.objects.filter(category=category)
    # Get entries ordered by date_time in descending order
    all_entries = Entry.objects.filter(tags__in=tags).order_by("-is_featured","featured_order","order").distinct()
    # Get which page we must display and get the corresponding entries
    page = request.GET.get('page')
    entries = get_entries_per_page(page, all_entries)
    # Return data to the template
    context.update(entries=entries, current_category=category)
    return render(request, 'main/entries_by_category_list.html', context)

def entry(request, id):
    # Get common info of all templates
    context = get_common_info(request)
    entry = get_object_or_404(Entry, id=id)
    # Return data to the template
    context.update(entry=entry)
    return render(request, 'main/entry.html', context)


# Return entries to be shown in app in JSON format 
def get_app_entries_json(request):
    # Get all important entries
    all_entries = Entry.objects.filter(show_in_app=True).order_by("-is_featured","featured_order","order")
    # Build a dictionary with the summary and body of these entries
    d = []
    for e in all_entries:
        v = {}
        v['pk'] = e.pk
        v['summary'] = e.summary
        v['body'] = e.body
        v['is_featured'] = e.is_featured
        tags = []
        for tag in e.tags.all():
            t = {}
            t['name'] = tag.name
            t['color'] = tag.color
            tags.append(t)
        v['tags'] = tags
        d.append(v)
    return JsonResponse(d, safe=False)

def get_tags_json(request):
    # Get all tags
    all_tags = Tag.objects.all()
    # Build a list with all tag names and colors
    tags_list = []
    for tag in all_tags:
        t = {}
        t['name'] = tag.name
        t['color'] = tag.color
        tags_list.append(t)
    return JsonResponse(tags_list, safe=False)

def redirect_old_web(request, exception=None):
    # Any page of style http://sindicat.net/lala that is not found 
    # will be redirected to http://antiga.sindicat.net/lala
    return redirect(settings.OLD_WEB + request.get_full_path())

@require_GET
def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /config/",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

posters/views.py
from django.shortcuts import render

# Create your views here.

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
    <head>
        <title>USTEC·STEs</title>
        <!-- Generic metadata -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta name="application-name" content="USTEC·STEs (IAC)">
        <meta name="description" content="USTEC·STEs (IAC) Unió Sindical dels Treballadors d'Ensenyament de Catalunya">
		<meta name="keywords" content="ustec, ustec·stes, ustec-stes, professors, mestres, ensenyament, educació, nomenaments, borsa, oposicions, interins, sindicat, iac, catalunya">
		<!-- Open Graph data -->
		<meta property="og:title" content="USTEC·STEs (IAC)" />
		<meta property="og:type" content="article" />
		<meta property="og:url" content="https://www.sindicat.net" />
		<meta property="og:description" content="{{ entry.summary | striptags }}" />
        <meta property="og:image" content="{% static 'images/logo_ustec_share.png' %}" />
        <!-- Tab icon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <!-- Bootstrap Core CSS -->
        <link href="{% static 'js-pkg/bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet" />
        <!-- Slick CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'js-pkg/slick/slick.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'js-pkg/slick/slick-theme.css' %}"/>
        <!-- Custom CSS -->
        <link href="{% static 'css/workgroup.css' %}" rel="stylesheet">
        <!-- GDPR CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-eu-cookie-law-popup.css' %}"/>
	<!-- cookies -->
	<script type="module" src="/static/js/js.cookie.min.js"></script>
	<script nomodule defer src="/static/js/js.cookie.min.js"></script>
        <!-- Matomo -->
        <script type="text/javascript">
        	var _paq = window._paq || [];
            _paq.push(['trackPageView']);
          	_paq.push(['enableLinkTracking']);
          	(function() {
            	var u="//matomo.sindicat.net/";
            	_paq.push(['setTrackerUrl', u+'matomo.php']);
            	_paq.push(['setSiteId', '{{workgroup_id}}']);
            	var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            	g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
          	})();
		</script>
    </head>
    <body class="eupopup eupopup-bottomright">
		<div class="content">
	        <nav class="navbar navbar-default" id="header">
	            <!-- Brand and toggle get grouped for better mobile display -->
	            <div class="container-fluid">
	                <div class="row">
	                    <div class="col-md-5 col-xs-12">
	                        <div class="navbar-header">
	                            <button id="header-menu-button" type="button" data-target="#header-menu-content" data-toggle="collapse" class="navbar-toggle">
	                                <span class="sr-only">Toggle navigation</span>
	                                <span id="header-menu-icon" class="glyphicon glyphicon-option-vertical"></span>
	                            </button>
	                            <a href="https://www.sindicat.net/" class="navbar-brand">
	                                <img id="logo" class="img-responsive" src="{% static 'images/logo_ustec.png' %}" />
	                            </a>
	                        </div>
	                    </div>
	                    <!-- Collection of nav links and other content for toggling -->
	                    <div class="col-md-7 col-xs-12" id="header-menu">
	                        <div id="header-menu-content" class="collapse navbar-collapse">
	                            <ul class="nav navbar-nav" id="header-menu-links">
	                                <li><a href="https://www.sindicat.net/p/qui-som">Qui som</a></li>
	                                <li><a href="https://www.sindicat.net/p/agenda">Agenda</a></li>
	                                <li><a href="https://www.sindicat.net/p/contacte/">Contacte</a></li>
	                                <li><a href="https://sindicat.net/espacioseguro/afilia.php">Afilia't</a></li>
	                            </ul>
	                            <div id="afilia-follow">
	                                <form id="login" class="form-inline">
	                                    <input type="text" class="form-control" id="user" tabindex="1" placeholder="Afiliat/da">
	                                    <input type="password" class="form-control" id="password" tabindex="2" placeholder="Contrasenya">
	                                    <button id="login-button" type="submit" class="btn">
	                                        <span id="login-icon" class="glyphicon glyphicon-circle-arrow-right"></span>
	                                    </button>
	                                </form>
	                                <form id="search" class="form-inline" action="https://duckduckgo.com/">
	                                    <input type="text" class="form-control" id="q" tabindex="3" placeholder="Cerca" name="q">
	                                    <button id="search-button" type="submit" class="btn">
	                                        <span id="search-icon" class="glyphicon glyphicon-search"></span>
	                                    </button>
	                                </form>
	                                <div id="follow">
	                                    <div class="social"><a href="https://www.facebook.com/groups/ustecstes/"><img src="{% static 'images/facebook.png' %}" /></a></div>
	                                    <div class="social"><a href="https://twitter.com/USTECSTEs"><img src="{% static 'images/twitter.png' %}" /></a></div>
	                                    <div class="social"><a href="https://www.youtube.com/usteccat"><img src="{% static 'images/youtube.png' %}" /></a></div>
	                                    <div class="social"><a href="http://t.me/ustec"><img src="{% static 'images/telegram.png' %}" /></a></div>
										<div class="social"><a href="https://www.instagram.com/ustecstes/"><img src="{% static 'images/instagram.png' %}" /></a></div>
	                                </div>
	                            </div>
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </nav>
	        {% include 'main_menu/main_menu.html' %}
	        {% include 'main/breadcrumb.html' %}
	        {% block content %}
	        {% endblock %}	        
		</div>
        <div id="visits">Número de visites avui: {{ visits }}</div>
		{% include 'main/footer.html' %}
        <!-- jQuery -->
        <script language="javascript" type="text/javascript" src="{% static 'js-pkg/jquery/jquery.min.js' %}"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'js-pkg/bootstrap/js/bootstrap.min.js' %}"></script>
        <!-- slick -->
        <script type="text/javascript" src="{% static 'js-pkg/slick/slick.js' %}"></script>
        <!-- workgroup javscript -->
        <script src="{% static 'js/workgroup.js' %}"></script>
        <script src="{% static 'js/calculs/increments_retributius_2018.js' %}"></script>        
        <script src="{% static 'js/calculs/paga_extra_2013.js' %}"></script>
        <script src="{% static 'js/assessoraments.js' %}"></script>
        <script src="{% static 'js/especialitat_borsa.js' %}"></script>
		<script src="{% static 'js/dades_plantilles.js' %}"></script>
		<!-- GDPR javascript -->
        <script src="{% static 'js/jquery-eu-cookie-law-popup.js' %}"></script>
	<script>
/*$( document ).ready(function() {


  if(Cookies.get('cartellVaga')!=1){
  

    var in6Hours = 1/4;

    Cookies.set('cartellVaga', '1', { domain: 'sindicat.net', expires: in6Hours }    );
    $( "body" ).append( "<div id='capaVaga' style='position:absolute;width: 100%;height: 100%;opacity: 95%;margin: 0px; background: #0e0e0e;'><a style='color:white;position: absolute;left:0;right:0;text-align: center;margin: 10px auto;' onclick=\"$('#capaVaga').remove();\">[Accedir a la web]</a><img    style='-webkit-user-select: none;position: absolute;left:0;right:0;text-align: center;margin:50px auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms; '    src='https://fast.sindicat.net/vaga.jpg' height='75%'></div>" );

    setTimeout(function() { 
      $("#capaVaga").remove();
    }, 18000);

  }

});
*/
	</script>
    </body>
</html>

main/templates/main/breadcrumb.html
{% if breadcrumb %}
<ul class="breadcrumb">
    {% for node in breadcrumb %}
        {% if forloop.last %}
            <li class="active">{{node.0}}</li>
        {% else %}
            <li><a href="{{node.1}}">{{node.0}}</a></li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}

main/templates/main/entries.html
{% for entry in entries %}
    {% if entry.is_featured %}
    <div class="entry featured-entry">
    {% else %}
    <div class="entry">
    {% endif %}
        {% include 'main/entry_list_item.html' %}
    </div>
{% endfor %}

main/templates/main/entries_by_category_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        {% include 'main/workgroup_menu_category.html' %}
        <div id="category_body">{{ current_category.body | safe }}</div>
        {% include 'main/entries.html' %}
        {% include 'main/pagination.html' %}
    </div>
{% endblock %}

main/templates/main/entries_by_tag_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
    	{% if not current_tag.is_hidden %}
        	<h1 class="category{{ current_tag.category.id }}">{{ current_tag.name }}</h2>
        {% endif %}
        <div>{{ current_tag.body | safe }}</div>
        {% include 'main/entries.html' %}
        {% include 'main/pagination.html' %}
    </div>
{% endblock %}

main/templates/main/entry_list_item.html
{% include 'main/tag_container.html' %}
{% include 'main/main_image.html' %}
{% if entry.body %}
    <a href="/e/{{entry.id}}">{{ entry.summary | safe }}</a>
{% else %}
    {{ entry.summary | safe }}
{% endif %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" id="container-index">
{% include 'main/workgroup_menu.html' %}
    <div class="row" id="content">
    {% if show_right_column %}
        {% if nomenaments_installed and nomenaments_num.items %}
            <div class="col-md-6 col-sm-12">
        {% else %}
            <div class="col-md-7 col-sm-12">
        {% endif %}
    {% else %}
        <div class="col-md-12">
    {%endif%}
    {% include 'main/entries.html' %}
    {% include 'main/pagination.html' %}
        </div>
    {% if show_right_column %}
        {% if nomenaments_installed and nomenaments_num.items %}
            <div class="col-md-6 col-sm-12" id="media">
        {% else %}
            <div class="col-md-5 col-sm-12" id="media">
        {% endif %}
        {% if nomenaments_installed %}
            {% include 'nomenaments/nomenaments_numero.html' %}
        {% endif %}
        {% include 'videos/featured_videos.html' %}
        {% include 'main/posters.html' %}
        {% include 'videos/videos.html' %}
        {% include 'main/twitter_timeline.html' %}
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

main/templates/main/pagination.html
{% if entries.paginator.num_pages > 1 %}
    <ul class="pagination">
        <li><a href="?page=1">|<</a></li>
        {% if entries.has_previous %}
            <li><a href="?page={{entries.previous_page_number}}"><<</a></li>
        {% else %}
            <li class="disabled"><a href="#"><<</a></li>
        {% endif %}
        {% if entries.has_next %}
            <li><a href="?page={{entries.next_page_number}}">>></a></li>
        {% else %}
            <li class="disabled"><a href="#">>></a></li>
        {% endif %}
        <li><a href="?page={{entries.paginator.num_pages}}">>|</a></li>
    </ul>
{% endif %}

main/templates/main/posters.html
<div id="posters" class="container-fluid">
{% comment %}
Recorrem el llistat de posters i si hi ha alguna imatge marcada com apaisada
fem que ocupi les dues columnes
{% endcomment %}
{% for poster in posters %}
    <div class="row">
        {% with posterimage=poster.posterimage_set.all.0 %}
        {% if posterimage.landscape_mode == 1 %}
            <div class="col-sm-12">
	                {% if posterimage.link %}
	                    <a href="{{ posterimage.link }}"><img src="{{ posterimage.image.url }}" alt="{{ posterimage.alt }}"></a>
	                {% else %}
	                    <a href="{{ posterimage.image.url }}"><img src="{{ posterimage.image.url }}" alt="{{ posterimage.alt }}"></a>
	                {% endif %}
            </div>
        {% endif %}
        {% endwith %}
    </div>
{% endfor %}



{% for poster in posters %}
    {% if forloop.counter0|divisibleby:2 %}
        <div class="row">
    {% endif %}
                {% with posterimage=poster.posterimage_set.all.0 %}
				{% if posterimage.landscape_mode == 0 %}
				<div class="col-sm-6">
				{% else %}
				<div class="d-none">
				{% endif %}
				{% endwith %}
            

                {# If the poster only has an image, show this image #}
                {% if poster.posterimage_set.all.count == 1 %}

                    {% with posterimage=poster.posterimage_set.all.0 %}
					{% if posterimage.landscape_mode == 0 %}
	                        {% if posterimage.link %}
	                            <a href="{{ posterimage.link }}"><img src="{{ posterimage.image.url }}" alt="{{ posterimage.alt }}"></a>
	                        {% else %}
	                            <a href="{{ posterimage.image.url }}"><img src="{{ posterimage.image.url }}" alt="{{ posterimage.alt }}"></a>
	                        {% endif %}
					{% endif %}
                    {% endwith %}
                {# If the poster has more than one image build a carousel #}
                {% else %}
                    {% with carousel_number=forloop.counter0 %}
                        <div id="carousel{{ carousel_number }}" class="poster-carousel">
                            {% for posterimage in poster.posterimage_set.all %}
                                <div>
                                    {% if posterimage.link %}
                                        <a href="{{ posterimage.link }}"><img src="{{ posterimage.image.url }}" alt="{{ posterimage.alt }}"></a>
                                    {% else %}
                                        <a href="{{ posterimage.image.url }}"><img src="{{ posterimage.image.url }}" alt="{{ posterimage.alt }}"></a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    {% endwith %}
                {% endif %}

                {% with posterimage=poster.posterimage_set.all.0 %}
				{% if posterimage.landscape_mode == 0 %}
            	</div>
				{% endif %}
				{% endwith %}



    {% if not forloop.counter0|divisibleby:2 or forloop.last %}
        </div>
    {% endif %}
{% endfor %}
</div>

{% comment %}
This code generates HTMl like this. We assume we have one poster with only 
one image and another one with two images and no specific links:
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <a href="/media/common/posters/dsc00647_9OQwVqS.jpg">
                <img src="/media/common/posters/dsc00647_9OQwVqS.jpg" alt="foto0" />
            </a>
        </div>
        <div class="col-sm-6">
            <div id="carousel1" class="poster-carousel">
                <div>
                    <a href="/media/common/posters/dsc00648.jpg">
                        <img src="/media/common/posters/dsc00648.jpg" alt="foto1" />
                    </a>
                </div>
                <div>
                    <a href="/media/common/posters/dsc00648.jpg">
                        <img src="/media/common/posters/dsc00650.jpg" alt="foto2" />
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endcomment %}

main/templates/main/tag_container.html
<div class="tag-container">
    {% for tag in entry.tags.all %}
        {% if not tag.is_hidden %}
            {% if tag.color %}
                <div class="tag" style="background-color: {{ tag.color }}">
            {% else %}
                <div class="tag category{{ tag.category.id }}">                      
            {% endif %}
                    <a class="hidden-xs" href="/t/{{ tag.short_name }}">{{ tag.name }}</a>
                </div>
        {% endif %}
    {% endfor %}
     {% if not entry.all_tags_hidden %}
        <br class="visible-xs"  />
        <span class="entry_date">{{ entry.date_time | date:"d/m/y" }}</span>
    {% endif %}
</div>