assessoraments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<course_type>/candidate_status', views.get_candidate_status, name='get_candidate_status'),
    path('<course_type>/courses_lists', views.courses_lists, name='courses_lists'),
    path('<course_type>/course_list_detail', views.courses_lists, name='course_list_detail'),
    path('<course_type>/course_list_email', views.courses_lists, name='course_list_email'),
    path('<course_type>/', views.get_candidate_data),
]

main/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views
from main.views import robots_txt

urlpatterns = [
    #url(r'^$', views.index),
    path('', views.index),
    #url(r'^robots.txt', robots_txt),
    path('robots.txt', robots_txt),
    #url(r'^c/(?P<short_name>[0-9a-z\-]+)/$', views.entries_by_category_list),
    path('c/<slug:short_name>/', views.entries_by_category_list),
    #url(r'^t/(?P<short_name>[0-9a-z\-]+)/$', views.entries_by_tag_list),
    path('t/<slug:short_name>/', views.entries_by_tag_list),
    #url(r'^e/(?P<id>[0-9]+)/$', views.entry),
    path('e/<int:id>/', views.entry),
    #url(r'^json/app_entries$', views.get_app_entries_json),
    re_path('^json/app_entries$', views.get_app_entries_json),
    #url(r'^json/tags$', views.get_tags_json),
    re_path('^json/tags$', views.get_tags_json),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.COMMON_MEDIA_URL, document_root=settings.COMMON_MEDIA_ROOT)

workgroup/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.apps import apps

handler404 = 'main.views.redirect_old_web'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('m/', include('main_menu.urls')),
    path('', include('main.urls'))
    # , path('afiliacio/', include('afiliacio.urls'))
]

if apps.is_installed('assessoraments'):
    urlpatterns.insert(0, path('assessoraments/', include('assessoraments.urls')))

if apps.is_installed('calculs'):
    urlpatterns.insert(0, path('calculs/', include('calculs.urls')))

if apps.is_installed('especialitat_borsa'):
    urlpatterns.insert(0, path('especialitat_borsa/', include('especialitat_borsa.urls')))

if apps.is_installed('dades_plantilles'):
    urlpatterns.insert(0, path('dades_plantilles/', include('dades_plantilles.urls')))

if apps.is_installed('simple_pages'):
    urlpatterns.insert(0, path('p/', include('simple_pages.urls')))

if apps.is_installed('afiliacio'):
    urlpatterns.insert(0, path('afiliacio/', include('afiliacio.urls')))

assessoraments/models.py
import locale
from django.db import models
from ckeditor.fields import RichTextField
from .utils import send_instructions_mail
from config.models import Config

class Instructions(models.Model):
    code = models.CharField(max_length=20, verbose_name='Codi')
    text_email = models.TextField(blank=True, verbose_name='Text correu electrònic')
    text_web = RichTextField(blank=True, verbose_name='Text web')
    class Meta:
        abstract = True
        verbose_name = 'instrucció'
        verbose_name_plural = 'instruccions'
    def __str__(self):
        return self.code
    
class InstructionsDocents(Instructions):
    class Meta:
        verbose_name = 'instrucció docents'
        verbose_name_plural = 'instruccions docents'

class InstructionsLaborals(Instructions):
    class Meta:
        verbose_name = 'instrucció laborals'
        verbose_name_plural = 'instruccions laborals'

# Create your models here.
class Candidate(models.Model):
    dni = models.CharField(max_length=10, verbose_name='DNI')
    name = models.CharField(max_length=50, verbose_name='Nom')    
    surname1 = models.CharField(max_length=50, verbose_name='Primer Cognom')
    surname2 = models.CharField(max_length=50, blank=True, verbose_name='Segon Cognom')
    phone = models.CharField(max_length=12, verbose_name='Telefon')
    email = models.EmailField(verbose_name='Correu electrònic')
    selected_course = None
    region = models.CharField(max_length=25, blank=True, verbose_name='Comarca')
    speciality_course = None
    observations = models.TextField(blank=True, verbose_name='Observacions')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Data i hora de la inscripció')
    # The mail has been sent correctly
    mail_sent = models.BooleanField(default=False, verbose_name='Correu enviat')
    # The membership has been checked and the candidate is member
    is_real_member = models.BooleanField(default=False, verbose_name='És afiliat')
    # Course assignation status    
    ASSIGNED = 'ASSIGNED'
    WAITLIST = 'WAITLIST'
    REFUSED = 'REFUSED'
    SITUATION_CHOICES = (
        (ASSIGNED, 'Assignat'),
        (WAITLIST, 'Llista d\'espera'),
        (REFUSED , 'Renúncia'),
    )
    assigned_status = models.CharField(default='WAITLIST', max_length=20,
                            choices=SITUATION_CHOICES,
                            verbose_name='Assignació assessorament')
    # If the candidate has no vacancy, set here his/her waitlist order. 0, otherwise
    wait_list = models.IntegerField(default=0, verbose_name="Ordre llista d'espera")
    # Data related to no members that  must be members to be able to do the course
    birthday = models.DateField(blank=True, null=True, verbose_name='Data de naixement')
    address = models.CharField(blank=True, max_length=100, verbose_name='Adreça')
    postal_code = models.CharField(blank=True, max_length=5, verbose_name='Codi Postal')
    city = models.CharField(blank=True, max_length=100, verbose_name='Població')
    school_name = models.CharField(blank=True, max_length=100, verbose_name='Nom del centre')
    school_city = models.CharField(blank=True, max_length=100, verbose_name='Població del centre')
    school_code = models.CharField(blank=True, max_length=8, verbose_name='Codi del centre')
    iban = models.CharField(blank=True, max_length=24, verbose_name='IBAN')
    current_speciality = None
    DEFINITIVE = 'DEFINITIVE'
    PROVISIONAL = 'PROVISIONAL'
    COMISSIO = 'COMISSIO'
    INTERIM = 'INTERIM'
    UNEMPLOYMENT = 'UNEMPLOYMENT'
    ALTRA = 'ALTRA'
    SITUATION_CHOICES = (
        (DEFINITIVE, 'Plaça definitiva'),
        (PROVISIONAL, 'Plaça provisional'),
        (COMISSIO, 'Comissió de serveis'),
        (INTERIM , 'Interinatge o substitucions'),
        (UNEMPLOYMENT, 'Atur'),
        (ALTRA, 'Altra'),
    )
    situation = models.CharField(blank=True, null=True, max_length=20,
                            choices=SITUATION_CHOICES,
                            verbose_name='Situació')
    territory = models.ForeignKey('Territory', on_delete=models.CASCADE, verbose_name='Territori', default=None, blank=True, null=True,)
    InstructionsType = None
    class Meta:
        abstract = True
        verbose_name = 'opositor'
        verbose_name_plural = 'opositors'
    def __str__(self):
        return self.surname1 + " " + self.surname2 + ", " + self.name
    def assign_course(self):
        self.assigned_status = 'ASSIGNED'
        self.wait_list = 0
    def get_instructions(self, text_type="text_email", closed_vaccancies=False):
        if self.assigned_status == 'ASSIGNED':
            if self.is_real_member:
                code = "ASSIGNATAFILIAT"
            else:
                code = "ASSIGNATNOAFILIAT"
        else:
            if not closed_vaccancies:
                code = "LLISTAESPERA"
            else:
                code = "SENSEPLACES"     
        instructions_text = getattr(self.InstructionsType.objects.filter(code=code)[0], text_type)
        instructions_text = self.fill_instructions_template(instructions_text)
        return instructions_text
    
    def fill_instructions_template(self, instructions):
        candidate_course = self.selected_course
        locale.setlocale(locale.LC_ALL, "ca_ES.UTF-8")
        # Replace each tag by its value
        instructions = instructions.replace("{{code}}", 
                                            candidate_course.code) \
                                   .replace("{{place}}", 
                                            candidate_course.place) \
                                   .replace("{{address}}", 
                                            candidate_course.address) \
                                   .replace("{{city}}", 
                                            candidate_course.city) \
                                   .replace("{{dates}}", 
                                            candidate_course.dates) \
                                   .replace("{{territory}}", 
                                            candidate_course.territory_contact.territory.name) \
                                   .replace("{{email}}", 
                                            candidate_course.territory_contact.email)
        return instructions
    
class CandidateDocents(Candidate):
    speciality_course = models.ForeignKey('SpecialityDocents', on_delete=models.CASCADE, related_name='speciality_course', default=None, null=True, verbose_name='Especialitat per a la qual et presentes')
    selected_course = models.ForeignKey('CourseDocents', on_delete=models.CASCADE, verbose_name='Assessorament')
    current_speciality = models.ForeignKey('SpecialityDocents', on_delete=models.CASCADE, related_name='current_speciality', default=None, blank=True, null=True, verbose_name='Especialitat actual')
    InstructionsType = InstructionsDocents
    class Meta:
        verbose_name = 'opositor docent'
        verbose_name_plural = 'opositors docents'

class CandidateLaborals(Candidate):
    speciality_course = models.ForeignKey('SpecialityLaborals', on_delete=models.CASCADE, related_name='speciality_course', default=None, null=True, verbose_name='Categoria professional per a la qual et presentes')
    selected_course = models.ForeignKey('CourseLaborals', on_delete=models.CASCADE, verbose_name='Assessorament')
    current_speciality = models.ForeignKey('SpecialityLaborals', on_delete=models.CASCADE, related_name='current_speciality', default=None, blank=True, null=True, verbose_name='Categoria professional actual')
    InstructionsType = InstructionsLaborals
    class Meta:
        verbose_name = 'opositor laboral'
        verbose_name_plural = 'opositors laborals'
    
class Course(models.Model):
    code = models.CharField(unique=True, max_length=10, verbose_name='Codi')
    speciality = models.CharField(max_length=50, verbose_name="Especialitat")
    territory_contact = None
    city = models.CharField(max_length=50, verbose_name='Població')
    place = models.CharField(max_length=100, verbose_name='Lloc')
    address = models.TextField(verbose_name='Adreça')
    dates = models.TextField(verbose_name='Dates')
    vaccancies = models.IntegerField(default=0, verbose_name='Places')
    closed = models.BooleanField(verbose_name='Assessorament tancat')
    CandidateType = None
    class Meta:
        abstract = True
        verbose_name = 'assessorament'
        verbose_name_plural = 'assessoraments'
        ordering = ['code']
    def __str__(self):
        return self.code
    
    def n_free_vaccancies(self):
        course_students = self.CandidateType.objects.filter(selected_course=self, assigned_status='ASSIGNED')
        free_vaccancies = self.vaccancies - len(course_students)
        return free_vaccancies
    
    def n_waitlist(self):
        waiting_list = self.CandidateType.objects.filter(selected_course=self, 
                                                assigned_status='WAITLIST') \
                                        .exclude(wait_list=-2)
        return len(waiting_list)
    
    def free_vaccancies(self):
        free_vaccancies = self.n_free_vaccancies()
        if free_vaccancies > 0:
            return True
        return False
    
    def reorder_waitinglist(self):
        course_waiting_list_ustec = self.CandidateType.objects.filter(selected_course=self, assigned_status='WAITLIST', is_real_member=True).exclude(wait_list=-2).order_by("date")
        course_waiting_list_no_ustec = self.CandidateType.objects.filter(selected_course=self, assigned_status='WAITLIST', is_real_member=False).exclude(wait_list=-2).order_by("date")
        i = 0
        for i in range(len(course_waiting_list_ustec)):
            course_waiting_list_ustec[i].wait_list = i + 1
            course_waiting_list_ustec[i].save()
        i = len(course_waiting_list_ustec)
        for j in range(len(course_waiting_list_no_ustec)):
            course_waiting_list_no_ustec[j].wait_list = i + 1

assessoraments/templates/assessoraments/candidate_status.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <h1>Dades de la inscripció</h1>
        <p><strong>DNI:</strong> {{candidate.dni}}
        <p><strong>Nom i cognoms:</strong> {{candidate.name}} {{candidate.surname1}} {{candidate.surname2}} 
        <p><strong>Assessorament:</strong>{{candidate.selected_course}}
        <p class="lead"><strong>Estat de la inscripció: <mark>{{ candidate.get_assigned_status_display }}</mark></strong></p>
    </div>
</div>
{% endblock %}

assessoraments/templates/assessoraments/candidate_status_form.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <h1>Consulta l'estat de la teva inscripció ({{ course_type }})</h1>
        <div class="col-md-5">            
            <form method="post">
                {% csrf_token %}
                <div class="has-error">
                    <span class="has-error help-block"> {{ form.non_field_errors|striptags }}</span>
               </div>
                {% for field in form %}
                    <div class="form-group {%if field.errors %}has-error{%endif%}">
                        {% if field.help_text %}
                            <p>{{ field.help_text | safe }}</p>
                        {% endif %}
                        {{ field.label_tag }}
                        {{ field }}
                        <span class="help-block">{{ field.errors|striptags }}</span>
                    </div>
                {% endfor %}
                <input class="btn btn-default" type="submit" value="Consulta" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

assessoraments/templates/assessoraments/course_description.html
{% load static %}
<h3>
	<span class="btn description_icon glyphicon glyphicon-chevron-down"
	      aria-hidden="true" 
	      data-toggle="collapse" 
	      data-target="#collapse{{forloop.counter0}}"
	      aria-expanded="false" 
	      aria-controls="collapse"
	      style="background-color: #e7e7e7">
	</span>
	{{ course.code }}
    {% if course.closed %}
        <img src="{% static 'images/assessoraments/tancat.jpg' %}">
    {% endif %}
</h3>
<p><strong>Població:</strong> {{ course.city }}</p>
<p><strong>Especialitat:</strong> {{ course.speciality }}</p>
<div class="collapse" id="collapse{{forloop.counter0}}">
	<p><strong>Lloc:</strong> {{ course.place }}</p>
    <p><strong>Adreça:</strong> {{ course.address }}</p>
    <div>
    	<strong>Sessions:</strong>
    	<div style="margin-left: 1em;">
   			{{ course.dates | safe }}
  		</div>
	</div>
	<p>
		<span style="margin-right:0.5em;">
{# 			<strong>Places totals:</strong> {{ course.vaccancies }}  #}
		</span>
		<span style="margin-right:0.5em;">
{# 	   		<strong>Places lliures:</strong> {{ course.n_free_vaccancies }} #}
	   	</span>
{# 	   	<strong>Llista d'espera:</strong> {{ course.n_waitlist }} #}
	</p>
</div>

assessoraments/templates/assessoraments/course_list_detail.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>{{code}}</h1>
        <table class="table table-bordered">
        <tr>
        	<th></th>
        	<th>Nom</th>
        	<th style="text-align: center;">Especialitat</th>
        	<th width="14%" style="text-align: center;"></th>
        	<th width="14%" style="text-align: center;"></th>
        	<th width="14%" style="text-align: center;"></th>
        	<th width="14%" style="text-align: center;"></th>
            <th width="14%" style="text-align: center;"></th>
        </tr>
        {% for candidate in candidates %}
        	<tr>
        		<td style="text-align: center; vertical-align:middle">{{forloop.counter}}</td>
        		<td style="vertical-align:middle">{{ candidate.surname1 }} {{ candidate.surname2 }}, {{ candidate.name }}</td>
        		<td style="text-align: center; vertical-align:middle">{{ candidate.speciality_course }}</td>
        		<td style="height:50px"></td>
        		<td style="height:50px"></td>
        		<td style="height:50px"></td>
        		<td style="height:50px"></td>
                <td style="height:50px"></td>
        	</tr>
        {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

assessoraments/templates/assessoraments/course_list_email.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>Llistat correus electrònics {{code}}</h1>
        <table class="table table-bordered">
        <tr>
        	<th>Nom</th>
        	<th>Especialitat</th>
            <th>Correu electrònic</th>
        </tr>
        {% for candidate in candidates %}
        	<tr>
        		<td>{{ candidate.surname1 }} {{ candidate.surname2 }}, {{ candidate.name }}</td>
        		<td>{{ candidate.speciality_course }}</td>
                <td>{{ candidate.email }}</td>
        	</tr>
        {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

assessoraments/templates/assessoraments/courses_lists.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <h1>Llistats ({{course_type}})</h1>
        <table class="table table-striped" width="50%">
        	<tr>
        		<th>Codi</th>
        		<th>Territori</th>
        		<th></th>
                <th></th>
        	</tr>
        {% for course in courses %}
        	<tr>
        		<td>{{ course.code }}</td>
        		<td>{{ course.territory.name }}
        		<td><a class="btn btn-info" href="{% url 'course_list_detail' course_type%}?type=attendance&course={{course.pk}}">Llistat Assitència</a></td>
                <td><a class="btn btn-info" href="{% url 'course_list_detail' course_type%}?type=email&course={{course.pk}}">Llistat Correus Electrònics</a></td>
        	</tr>
        {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

assessoraments/templates/assessoraments/index.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
<div class="container">
    {{title | safe}}
    {{intro | safe}}
    {% if not all_courses_closed %}
        <div class="row">        
            <div class="col-md-5">
            	<h2>Inscripció</h2>
                {{full_form_intro | safe}}
                <form method="post">
        			{% csrf_token %}
        			<!-- {{ form.as_p }}-->
                    {% for field in form.hidden_fields %}
                        {{ field }}
                    {% endfor %}
        			{% for field in form.visible_fields %}
        				<div class="form-group {%if field.errors %}has-error{%endif%}">
                            {% if field.help_text %}
                                <p>{{ field.help_text | safe }}</p>
                            {% endif %}
    	    				{{ field.label_tag }}
    						{% if field|is_radio %}
    							<div style="margin-left: 2em">
    								{% for radio in field %}
    									<div class="form-check">
    									{{ radio }}
    									</div>
    								{% endfor %}
    							</div>
    						{% else %}      
    							
    							{{ field }}
    						{% endif %}
    						<span class="help-block">{{ field.errors|striptags }}</span>
    					</div>
    				{% endfor %}
        		<input class="btn btn-default" type="submit" value="Envia" />
    			</form>
    		</div>
    		<div class="col-md-7">
    			<h2>Informació dels assessoraments oferts</h2>
    			<div class="container-fluid">
    				<div class="col-md-6">
    					{% for course in courses %}							
    						{% if forloop.counter0|divisibleby:2 %}
    							{% include 'assessoraments/course_description.html' %}
     						{% endif %}					
        				{% endfor %}
    				</div>
    				<div class="col-md-6">
        				{% for course in courses %}
    						{% if not forloop.counter0|divisibleby:2 %}					
    			            	{% include 'assessoraments/course_description.html' %}
     						{% endif %}		
        				{% endfor %}	
    				</div>			        
    		    </div>
            </div>        
        </div>
    {% endif %}
    {{footer | safe}}
</div>
{% endblock %}

assessoraments/templates/assessoraments/not_afiliat_candidate.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
<div class="container">
<p>Hem detectat que no est&agrave;s afiliat/da i adscrit/a a Barcelona, i per tant, no podràs inscriure't a l'assessorament, ja que aquests són exclusivament per a persones afiliades.</p>
<p>A efectes d'aquests assessoraments una persona es considera afiliada si ja ha pagat una quota trimestral, la qual cosa implica en el cas de Barcelona haver-se afiliat abans del final de l'any 2020.</p>
<p>Si creus que es tracta d'un error, escriu un correu a oposicionsbcn@sindicat.net amb les teves identificatives.</p>
<p>Si estàs afiliat/da, però adscrit/a a un altre territori, posa't en contacte amb el territori en qu&egrave; pagues la teva quota.</p>
</div>
{% endblock %}

assessoraments/templates/assessoraments/sent.html
{% extends 'main/base.iframe.html' %}
{% load static %}
{% load forms_tags %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <h1>Les teves dades s'han enviat correctament.</h1>
        <p>{{instructions|safe}}</p>
    </div>
</div>
{% endblock %}